### PR TITLE
Changed The "A" action to simulate a jump button keybind.

### PR DESCRIPTION
**Pull request by SuperKael**
Instead of directly causing a jump action, this makes it compatible with
things like the jetpacks from the Simply Jetpacks mod.

### CODE REVIEW

**Comment by SuperKael** [comment]
Nevermind, it's clear that this has been abandoned, at least for the time being. I will be continuing to make improvements and bugfixes on my own fork.

**Comment by MrCrayfish** [comment]
I did see this, I'm just busy with other work right now.

**Comment by MrCrayfish** [comment]
Reopen and I will merge

**Comment by SuperKael** [comment]
Well I would, but since I figured that the project was abandoned, I decided to just go on and do all kinds of stuff with what effectively became my own version. As such, if this PR were to be merged now, it would bring all that stuff in... If you're fine with that, I made a different PR for that. If not, then I'll do whatever you'd rather me do.

**Pull request closed without merging**
