### PR TITLE
New Button Remapping with GUI and API. Continuation of #73

### PR DESCRIPTION
**Pull request by Fernthedev**
So I'm not really sure if making another PR with the same code as #73 with extra changes is a good idea. But to cut it clear, it includes #73 and this:

- Migrated ButtonBindings old system to a new Controller Button System. The new system has a simple to use but strict API which can be managed when mods are initialized. It also includes a GUI that is easily manageable.  The mod loads the action registry file once FML has called FMLLoadCompleteEvent or in other words Minecraft finishes loading and enters the main menu.
- ButtonBinding class is now mutable and contains a defaultButtonId int.
- ButtonActions can still be used from ButtonRegistry.ButtonActions.ACTION.getButton();
- This was achieved using an extra dependency, specifically one of my own projects, which is my config manager. It can be found [here](https://github.com/Fernthedev/fern-configmanager) and it uses Gson and Okio

Note however that there are new translation keys that have yet to be added to other languages. For now, English is the main language supported in this PR. I will see if I can add Spanish later on but it is as far as I can go.

To use the API, it is quite simple:
```java
// Action is used to refer to an action that is set to a button. 
// ActionData is just a data class that refers to two translation keys: the action's description such as Jump and the action's category, such as "Gameplay" or "MyMod"
ButtonRegistry.getButton("action"); // Returns the ButtonBinding instance. Throws exception if registerButton has not been called.
ButtonRegistry.registerButton("action", actionData, buttonBinding); // Registers the action in the registry. Throws an exception if the action is already registered.
ButtonRegistry.getAction(String action); // Get's the action translation keys.
ButtonRegistry.getButtonBindings(); // Return's a copy of the registry which will not modify the orginal
ControllerProperties.saveActionRegistry(); // Saves the current controller action registry as a JSON file. Theoretically it should only overwrite settings that are registered in memory, as is the case when a mod registers an action, saves it but then the next time the game starts the mod is no longer present to avoid resetting it. This has not been tested however.
ControllerProperties.loadActionRegistry(); // Loads the action registry from the file.
```

The code may look messy but it works for remapping actions to different buttons.

The GUI looks like this:
image

A more optimal design choice might be making replacing the text showing what buttons are assigned to icons. It can also be linked to the Icon Preference. I would have done it if I knew how to use OpenGL but unfortunately I don't.

If it's better, #73 can be closed because this is a continuation of that PR. 
Sorry in advance if the code and this PR seem sloppy.

I'm open to criticism of code quality and features' implementation.

### CODE REVIEW

**Comment by MrCrayfish** [comment]
I love the effort thats gone into this PR and I will test it out soon. My first concern is (this applies to creating a PR for anyones project) is that you are using the wrong code style. I have included a Project.xml file in the base directory you can grab for the code style in IntelliJ. 

My next concern is the use of additional dependecies, notably Lombok. It's fine to use in your own personal projects but I personally don't use it (regardless of it's benefits). It also adds more confusion to people who want to fork this project. I've not been able to run this PR even though I've installed the plugin.

I feel a lot of personal development habits have been put into this PR. Not saying they are bad but definitely weird putting into another developers project. My feedback is to redo this PR, seperate features as suggested in the last one, apply my feedback, then I will consider merging.

**Comment by Fernthedev** [comment]
Ah, so what you're saying basically is this: 
- Remove Lombok
- Use project.xml codestyle.

Well I use Intellij IDEA but how would I know if it's using your project.xml code style or not? Thanks for being understandable as I'm quite new to making PRs. I only use Lombok since it's easier to read and write imo instead of writing manually constructors and such but it's understandable that it doesn't fit everyone. Once I have applied the changes, would I just commit to this PR or make a new one so you get notified?

**Comment by Fernthedev** [comment]
So for now I removed Lombok and applied the code style setting. Anything else missing? By the way, I forgot to mention I ported all the new features back to 1.14.4 as in my opinion it should still be supported and later on I saw Forge is planning to make it LTS. The features were all first made in 1.15.X and then merged into 1.14.X. The prebuilt jars can be found at my [repo](https://github.com/Fernthedev/Controllable/releases/tag/0.8.3)

**Comment by agentwolf88** [comment]
Can you please port to 1.12.2? :(

**Comment by Fernthedev** [comment]
> Can you please port to 1.12.2? :(

Not only is 1.12 unsupported by Forge, the user base is small. There is no point in using 1.12 since 1.14 and 1.15 are just fine. While most modpacks may be 1.12, they aren't a reason to support 1.12 or other older versions such as 1.7.10 or even 1.6.4.

**Comment by agentwolf88** [comment]
The user base in 1.12.2 is too small??

**Pull request closed without merging**
