### PR TITLE
Fix directions of dpad buttons

### LINKED ISSUE #180: DPAD Left and right icons swapped
i already tried to bring this to your attention in #116, but didn't have proof, which I now do (at [this link](https://drive.google.com/file/d/1YO2RXN6tviwlV83uq51a21HzjgiKvhqa/view?usp=sharing))
as you can clearly see, the left and right DPAD icons are swapped (This is a screenshot from an april 3rd build, i'll tell you if it's still in the latest build)

### PR DESCRIPTION
**Pull request by vtenfys**
Fixes left/right dpad buttons being in the wrong direction.

Closes #180

### CODE REVIEW

**Comment by MrCrayfish** [comment]
The playstation icon set also needs to be switched.

**Comment by vtenfys** [comment]
Ah yes, I spotted that left/right are already correct on PS but didn't notice up/down are wrong

**Comment by vtenfys** [comment]
done!

**Comment by MrCrayfish** [comment]
It was actually the left and right that needed to be switched. Icons are based on the physical buttons. The point on the playstation icons is actually the opposite side. Slightly confusing.
image

**Comment by vtenfys** [comment]
Ah thanks for pointing that out, should be alright now!

**Pull request merged**
