### PR TITLE
xInput Icons and fixes bug #30.

### PR DESCRIPTION
**Pull request by FusionLord**
Added XInput icons;
Added icon slider in the SettingsScreen; #35;
    Slider populates based on an enum for ease of adding new icons in the future;
alt text
alt text

### CODE REVIEW

**Comment by MrCrayfish** [comment]
I'm confused about the reloading. Doesn't it already do that? I just tested on the current version and it works. Is there an underlying issue I don't know about?

**Comment by FusionLord** [comment]
> 
> 
> I'm confused about the reloading. Doesn't it already do that? I just tested on the current version and it works. Is there an underlying issue I don't know about?

My bad, I had played this mod a while back and ControllerList didn't update back then. I removed that code from the PR.

**Comment by MrCrayfish** [comment]
I hate to be that guy but for the future please keep different bug fixes and features in seperate PRs. I squash merge so it will only appear as one commit.

**Comment by FusionLord** [comment]
Would you like me divide these up?

**Comment by FusionLord** [comment]
Not sure why Intellij pushed that commit to this branch I made a new branch for that bugfix.

**Comment by FusionLord** [comment]
Not sure why Intellij pushed that commit to this branch I made a new branch for that bugfix.

**Pull request closed without merging**
