### PR TITLE
New translation - Spanish (Spain) || Español (España)

### PR DESCRIPTION
**Pull request by raulsmartin**

### CODE REVIEW

**Comment by MrCrayfish** [comment]
Thank you!

**Comment by MrCrayfish** [comment]
Hey @raulsmartin , I am currently in the process of relicensing Controllable to a more suitable license. I would like your permission to relicense your contributions to Controllable under MIT.

**Comment by raulsmartin** [comment]
> 

Yeah! You have my permission

**Comment by raulsmartin** [comment]
In deed, I can translate the latest version if you need, I don't have much work right now and I've seen that Controllable has grown since my last contribution.

**Pull request merged**
