### PR TITLE
Fix language pt-BR file (for 1.15.X, 1.16.X)

### PR DESCRIPTION
**Pull request by hugoalh**
Issue found in branch `1.15.X` and `1.16.X`, the file format should be `pt_br.json` instead of `pt_br.lang`. Only renamed file without change any content.

### CODE REVIEW

**Comment by MrCrayfish** [comment]
I've just released some big updates and more changes to the lang file. Are you able to update this to the latest version?

**Comment by hugoalh** [comment]
@D-H-U is actually the translator of pt-BR (from pull request #53), I only resolve the file name issue :)

So @D-H-U can you update the file?

**Comment by D-H-U** [comment]
Sorry, I was away for a while, because of problems with my cell phone. I'll do everything as soon as possible.

**Comment by hugoalh** [comment]
*Issue resolved by owner.*

**Pull request closed without merging**
