### PR TITLE
add second joycon mapping due to bug in glfw

### PR DESCRIPTION
**Pull request by theofficialgman**
https://github.com/glfw/glfw/issues/1901

### CODE REVIEW

**Comment by MrCrayfish** [comment]
Submit controller mappings to the SDL Game Controller DB
https://github.com/gabomdq/SDL_GameControllerDB

**Comment by theofficialgman** [comment]
@MrCrayfish re-open this. This mapping has no place in the community mapping database for SDL2. SDL2 has no bug, it does not need this mapping. 

GLFW (a java library which among other things allows for gamecontroller mapping) has a bug in it with the sdl2 gamecontroller mapping function. They reimplemented the function (incorrectly) and do not use sdl2 itself. If you had clicked on the issue report, you would have understood that. You are using the GLWF library for this, there is no separated "patched" gamecontrollerdb.txt file which works around the GLFW bug, so it should be merged here.

**Comment by MrCrayfish** [comment]
Regardless, this is not the appropriate place to resolve a GFLW bug.

**Comment by theofficialgman** [comment]
GLFW gets packed in with lwjgl 3, shipped with minecraft
minecraft does NOT fix bugs or backport fixes in lwjgl. 
This bug in GLFW will remain in minecraft forever until GLFW fixes the bug, then lwjgl 3 updates their GLFW source, and then finally minecraft moves on to use a newer lwjgl (currently 3.2.2 is still used from 2019).

Like I said, the community gamecontroller mapping is for sdl2, that does not have any issues, it does not belong there. The only logical place to workaround this bug is in this repo any any repo that uses lwjgl for controller input. The mapping for GLFW does not match the official sdl2 controller mapping (as seen by the bug), so you should not be using a straightup copy of the mapping from the community repo.

**Pull request closed without merging**
